name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: hasnainmakada-99
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Kolkata
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%
          
          # Activity plugin
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          
          # Notable contributions
          plugin_notable: yes
          plugin_notable_repositories: yes
          
          # Lines of code
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          
          # Disable achievements to save space
          plugin_achievements: no