# name: "📚 latest Blog"

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "*/5 * * * *"

# jobs:
#   update_blogs:
#     name: "Update With Latest Blogs"
#     runs-on: ubuntu-latest
#     steps:
#       - name: "📥  Fetching Repository Contents"
#         uses: actions/checkout@main

#       - name: "📚  Hashnode Updater"
#         uses: "varunsridharan/action-hashnode-blog@1.1.1"
#         with:
#           USERNAME: "HasnainMakada" # Hashnode Username
#           COUNT: 4 # MAX Visisble
#           STYLE: "blog-grid"
#           BLOG_URL: "https://hasnainm.hashnode.dev/"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: 'Hashnode Blogs'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: 'Hashnode Latest Blogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch Repository Contents'
        uses: actions/checkout@main

      - name: 'Hashnode Blog Action'
        uses: 'Sachin-chaurasiya/hashnode-blog-action@main'
        with:
          HASHNODE_PUBLICATION_NAME: 'hasnainm.hashnode.dev'
          POST_COUNT: 4
          FORMAT: 'stacked'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
